version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: demoDB_Arun
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
