version: '3'
services:
  flask-app:
    build: ./app  # Path to your Flask app directory containing Dockerfile
    ports:
      - "5000:5000"  # Map container port to host port
    environment:
      - FLASK_ENV=development  # Set Flask environment
    depends_on:
      - mysql-db  # Depend on the mysql-db service

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set MySQL root password
      MYSQL_DATABASE: DBName  # Set the database name
      MYSQL_USER: root  # Set MySQL user
      MYSQL_PASSWORD: root  # Set MySQL password
    ports:
      - "3306:3306"  # Map container port to host port
