version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shivdb_17aug
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
